# Generated by Django 5.2 on 2025-05-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='es_intencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donacion',
            name='validada',
            field=models.BooleanField(default=False),
        ),
    ]
