# Generated by Django 5.2 on 2025-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0004_campana_nombre_campana_donante_ocupacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='latitud',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campana',
            name='longitud',
            field=models.IntegerField(),
        ),
    ]
