# Generated by Django 5.2 on 2025-06-16 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0005_alter_campana_latitud_alter_campana_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='preguntas_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=255)),
                ('respondida', models.BooleanField(default=False)),
                ('fecha_pregunta', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
