# Generated by Django 5.2 on 2025-06-17 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0006_preguntas_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='respuestas_representante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.preguntas_usuario')),
                ('id_representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.representante_org')),
            ],
        ),
    ]
