# Generated by Django 5.2 on 2025-06-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0008_alter_representante_org_credencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('basic', 'Básico'), ('level', 'Nivel'), ('social', 'Social'), ('rare', 'Raro/Especial')], max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('required_value', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='campana',
            name='es_emergencia',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donations', models.IntegerField(default=0)),
                ('emergency_donations', models.IntegerField(default=0)),
                ('different_centers', models.IntegerField(default=0)),
                ('app_shares', models.IntegerField(default=0)),
                ('history_views', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('years_active', models.IntegerField(default=0)),
                ('donante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.donante')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.achievementdefinition')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.donante')),
            ],
            options={
                'unique_together': {('donante', 'achievement')},
            },
        ),
    ]
