# Generated by Django 5.2 on 2025-06-19 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '00010_populate_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='id_centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.centro_donacion'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='centro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.centro_donacion'),
        ),
    ]
