# Generated by Django 5.2 on 2025-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0011_alter_campana_id_centro_alter_donacion_centro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='latitud',
            field=models.DecimalField(decimal_places=7, default=-33.4489, help_text='Latitud en formato decimal (ej:-33.4489)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='campana',
            name='longitud',
            field=models.DecimalField(decimal_places=7, default=-70.6693, help_text='Longitud en formato decimal (ej:-70.6693)', max_digits=10),
        ),
    ]
