# Generated by Django 5.2 on 2025-06-20 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0012_alter_campana_latitud_alter_campana_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='latitud',
            field=models.DecimalField(decimal_places=10, help_text='Latitud en formato decimal (ej:-33.4489)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='campana',
            name='longitud',
            field=models.DecimalField(decimal_places=10, help_text='Longitud en formato decimal (ej:-70.6693)', max_digits=15),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True, verbose_name='FCM Token')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'db_table': 'device_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx'), models.Index(fields=['token'], name='device_toke_token_e218ea_idx')],
            },
        ),
    ]
