# Generated by Django 5.2 on 2025-06-20 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0013_alter_campana_latitud_alter_campana_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante_org',
            name='credencial',
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cloudinary_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.representante_org')),
            ],
        ),
    ]
